### ISSUE TITLE
Attribute parsing error- http://digst.dk/oiosaml/basic_privilege_profile

### ISSUE THREAD

**Issue by theroys** [digst/OIOSAML.Java#68]
OIOSAML code fails to parse attribute http://digst.dk/oiosaml/basic_privilege_profile throws following error
java.lang.ClassCastException: dk.gov.oio.saml.oiobpp.PrivilegeList cannot be cast to javax.xml.bind.JAXBElement
        at dk.gov.oio.saml.oiobpp.OIOBPPUtil.parse(OIOBPPUtil.java:38)
        at dk.gov.oio.saml.session.AssertionWrapper.<init>(AssertionWrapper.java:155)
        at dk.gov.oio.saml.servlet.AssertionHandler.handlePost(AssertionHandler.java:164)
        at dk.gov.oio.saml.servlet.DispatcherServlet.doPost(DispatcherServlet.java:211)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)

The result is AssertionWrapper getPrivilegeList() always returns null

**Comment by TauBeblein** [comment]
In OIOSAML 3.1.0 you should also have this error log statement "Failed to parse input string: {}" it might be relevant for a solution.
I think that the unmarshaller delivered by your JAXB context is a little different from the one used in OIOBPPUtilTest.
My guess is that if the input is valid the parse method should be able to handle both.
